TYPO3:
  Flow:
    object:
      excludeClasses:
        'gedmo.*': ['.*']
        'mailgun.*': ['.*']
        'guzzlehttp.*': ['.*']
        'react.*': ['.*']

Ttree:
  Mailgun:
    key: 'set-your-own-api-key'
