TYPO3:
  Flow:
    object:
      excludeClasses:
        'gedmo.*': ['.*']
        'mailgun.*': ['.*']
        'guzzlehttp.*': ['.*']
        'react.*': ['.*']

Ttree:
  Mailgun:
    privateKey: 'key-use-your-own'
    publicKey: 'pubkey-use-your-own'
